### ISSUE TITLE
Request : Add documentation or hex templates

### ISSUE THREAD

**Issue by KillzXGaming** [PredatorCZ/XenoLib#2]
I would really appreciate some form of documentation to help understand the formats better either as template or documentation (like c code or text on how the structures are setup).

**Comment by PredatorCZ** [comment]
No need, structures are stored in source/header files in the source directory.
But be aware, some structures (mostly main header for V1 MXMD) are using custom fields.

**Comment by KillzXGaming** [comment]
Ah i see thank you.
