### ISSUE TITLE
Unable to use the tools due to the cmd returning "string too long"

### ISSUE THREAD

**Issue by XeroGrav** [PredatorCZ/XenoLib#5]
Hello, sorry if this is an obvious answer but I hadn't seen anyone have this issue. When I drag n' drop the XC3 tex/nx/m to the the tex_to_dds it generates an error and after a attempting to process part of the batch, it crashes.
 
![image](https://user-images.githubusercontent.com/110943572/183776781-5e2f11e2-bdad-45ee-92ab-cf4f334b08be.png)

If I were to open the cmd I receive this error 
![image](https://user-images.githubusercontent.com/110943572/183776829-1009f033-a531-40dc-ac45-0468f4837ddf.png)

I'm not quite sure if I'm missing something but I can't even open the xenoblade_toolset.exe without it closing immediately.

**Comment by PredatorCZ** [comment]
Interesting filenames you got there.
You can extract correct filenames with bms script I left on xentax forum.

**Comment by XeroGrav** [comment]
Thanks for the response and yeah this was an attempt to see if the naming affected the files in some way. lol I did use the bms script but it outputs the tex/nx/m folder using these filenames 
![image](https://user-images.githubusercontent.com/110943572/183913942-df115cf1-d8b0-4aa9-a021-2f0048069c65.png)

Which ends up in the same issue.
![image](https://user-images.githubusercontent.com/110943572/183913747-6c755997-9572-4cf9-99c7-37dcf34d2295.png)

What could be causing these errors?

**Comment by PredatorCZ** [comment]
You're right, got the same error. I normally use wine to test windows stuff.

**Comment by XeroGrav** [comment]
At least it wasn't just me. I run it natively on Windows 10 Pro 64-bit on OS Build 19044.1826

**Comment by PredatorCZ** [comment]
Should be now fixed in 2nd preview.

**Comment by XeroGrav** [comment]
Can confirm that it's working. Thank you so much!

![image](https://user-images.githubusercontent.com/110943572/184253314-5779f424-af19-4f4e-a137-f8c622f05b09.png)
