### ISSUE TITLE
Using Library

### ISSUE THREAD

**Issue by krodante** [PredatorCZ/XenoLib#7]
Hello! Thank you for creating this library!

This isn't really an issue, I'm just looking for instructions on how to run this project. I'm not a C developer, but I'd like to use this library to convert raw .bdats to .json. How do I install and run the project? I (think) I've been able to install it using Visual Studio connected to WSL, and I'd like to be able to run spike in the command line, but I'm not sure what I'm missing. 

I've also seen that the bdat storage structure in XC3 has changed from XC2, and I would love to contribute to some of the parsing. Any help would be greatly appreciated! Thank you!

**Comment by PredatorCZ** [comment]
Hi.
Toolset is in preview state, so releases are not very visible, but you can grab already built binaries in releases (https://github.com/PredatorCZ/XenoLib/releases).

If you still want help with setting up the project itself, let me know (but you don't need to use WSL or VS at all).

**Comment by krodante** [comment]
Thank you! I just downloaded the P4 release for win64. I tried to open `xenoblade_toolset.exe` as admin but the window immediately closed.

Then I tried PowerShell with:
```
PS C:\workspace\XenobladeToolset-win64> .\xenoblade_toolset.exe
⚠  No parameters provided, entering scan mode and generating config.
PS C:\workspace\XenobladeToolset-win64 (1)> .\xenoblade_toolset.exe bdat_to_json
⛔ Insufficient argument count, expected parameters.
```

**Comment by PredatorCZ** [comment]
You can use supplied .cmd file, they act as drag&drop.

**Comment by krodante** [comment]
Got it working by going to the XenobladeToolset-win64 directory and running `.\bdat_to_json.cmd path\to\bdat`. Thank you for your help!
